language: rust
rust:
- stable
sudo: false
os:
- linux
addons:
  apt:
    packages:
    - libudev-dev
cache:
  directories:
  - "$HOME/.cargo"
  - target
matrix:
  fast_finish: true
  allow_failures:
  - rust: nightly
env:
  matrix:
  - CARGO_FEATURES=
  - CARGO_DEFAULT_FEATURES=false
  global:
  - CARGO_QUIET=
before_install:
- curl -L https://github.com/arcnmx/ci/archive/0.2.tar.gz | tar -xzC $HOME && . $HOME/ci-0.2/src
script:
- cd $TRAVIS_BUILD_DIR
- cargo test
- cargo build
deploy:
  provider: script
  script: 'true'
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_RUST_VERSION = stable && $CARGO_DEFAULT_FEATURES != false"
before_deploy:
- cd $TRAVIS_BUILD_DIR
- cargo doc
after_deploy:
- cd $TRAVIS_BUILD_DIR
- cargo pages-publish
- cargo package
- cargo publish
